server:
  port: 8084

  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  datasource:
    url: jdbc:h2:mem:chessclub_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["metrics", "beans", "mappings", "health"]