server:
  port: 8084

  compression:
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  datasource:
    url: jdbc:h2:mem:chessclub_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  # Add validation properties
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: ["metrics", "beans", "mappings", "health"]

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: za.co.tangentsolutions.chessclub.controllers